### ISSUE TITLE
Docker json decoding error

### ISSUE THREAD

**Issue by postwarbreakout** [systemli/prometheus-jitsi-meet-exporter#106]
I've been running the exporter as binary on our jitsi host for a while now and it works well, but I'd like to slowly switch all these simple exporters to docker containers, where I'm now running into the following error:

```
# docker logs prometheus_jitsi_meet_exporter_1
json decoding error: json: cannot unmarshal object into Go struct field videoBridgeStats.conference_sizes of type []int
json decoding error: json: cannot unmarshal object into Go struct field videoBridgeStats.conference_sizes of type []int
```
I'm using the docker image 1.2 and jitsi-meet 2.0.7439-1.
It's possible to curl the stats from the monitoring server:

````
# curl -s http://jitsi:8888/stats | jq
{
  "largest_conference": 0,
  "jigasi_detector": {
    "sip_in_graceful_shutdown_count": 0,
    "transcriber_count": 0,
    "sip_count": 0
  },
  "conference_sizes": {
    "average": null,
    "max": 0,
    "min": 0,
    "total_value": 0,
    "total_count": 0,
    "discarded": 0,
    "buckets": {
      "0_to_1": 0,
      "1_to_2": 0,
      "2_to_3": 0,
      "3_to_5": 0,
      "5_to_10": 0,
      "10_to_20": 0,
      "20_to_50": 0,
      "50_to_100": 0,
      "100_to_200": 0,
      "200_to_300": 0,
      "300_to_400": 0,
      "400_to_500": 0,
      "500_to_max": 0,
      "p99_upper_bound": -1,
      "p999_upper_bound": -1
    }
  },
  "total_conferences_created": 307,
  "threads": 28,
  "jingle": {
    "received": {
      "source-add": 695,
      "session-accept": 771,
      "transport-info": 765,
      "session-terminate": 18,
      "source-remove": 130
    },
    "sent": {
      "source-add": 1942,
      "session-terminate": 40,
      "session-initiate": 771,
      "source-remove": 265
    }
  },
  "bridge_failures": {
    "participants_moved": 0
  },
  "total_participants": 848,
  "participant_notifications": {
    "ice_failed": 0,
    "request_restart": 18
  },
  "queues": {},
  "jigasi": {
    "rejected_requests": 0,
    "accepted_requests": 0,
    "requests_failed_no_instance": 0,
    "requests_failed_xmpp_not_connected": 0,
    "instance_errors": 0,
    "instance_timeout": 0,
    "retries": 0
  },
  "bridge_selector": {
    "total_least_loaded_in_region_group": 0,
    "lost_bridges": 0,
    "total_not_loaded_in_region_in_conference": 0,
    "in_shutdown_bridge_count": 0,
    "total_not_loaded_in_region_group": 0,
    "operational_bridge_count": 1,
    "total_not_loaded_in_region_group_in_conference": 0,
    "total_least_loaded_in_region_group_in_conference": 0,
    "total_least_loaded": 216,
    "total_least_loaded_in_region": 0,
    "total_split_due_to_load": 0,
    "total_least_loaded_in_region_in_conference": 0,
    "total_not_loaded_in_region": 0,
    "total_split_due_to_region": 0,
    "bridge_count": 1,
    "total_least_loaded_in_conference": 0
  },
  "jibri": {
    "total_sip_call_failures": 0,
    "live_streaming_pending": 0,
    "recording_pending": 0,
    "live_streaming_active": 0,
    "total_recording_failures": 0,
    "sip_call_pending": 0,
    "sip_call_active": 0,
    "total_live_streaming_failures": 0,
    "recording_active": 0
  },
  "endpoint_pairs": 0,
  "conferences": 0,
  "participants": 0
}
```

**Comment by fiskerendk** [comment]
Hi,

We are after upgrading jitsi now experiance the exact same problem.

root@meet:/etc/nginx# service prometheus-jitsi-meet-exporter status
● prometheus-jitsi-meet-exporter.service - stats exporter for jicofo listening on port 9888
     Loaded: loaded (/lib/systemd/system/prometheus-jitsi-meet-exporter.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-08-31 14:57:59 CEST; 14s ago
   Main PID: 42870 (prometheus-jits)
      Tasks: 8 (limit: 28724)
     Memory: 2.1M
     CGroup: /system.slice/prometheus-jitsi-meet-exporter.service
             └─42870 /usr/local/bin/prometheus-jitsi-meet-exporter

Aug 31 14:57:59 domain systemd[1]: Started stats exporter for jicofo listening on port 9888.
Aug 31 14:58:12 domain prometheus-jitsi-meet-exporter[42870]: json decoding error: json: cannot unmarshal object into Go struct field videoBridgeStats.conference_sizes of type []int


Curl result is like topic starter:
root@meet:/etc/nginx# curl -s http://127.0.0.1:8888/stats
{"jibri_detector":{"count":2,"available":2},"largest_conference":0,"jigasi_detector":{"sip_in_graceful_shutdown_count":0,"transcriber_count":0,"sip_count":0},"conference_sizes":{"average":null,"max":0,"min":0,"total_value":0,"total_count":0,"discarded":0,"buckets":{"0_to_1":0,"1_to_2":0,"2_to_3":0,"3_to_5":0,"5_to_10":0,"10_to_20":0,"20_to_50":0,"50_to_100":0,"100_to_200":0,"200_to_300":0,"300_to_400":0,"400_to_5 ....

However the following error is experianced when using curl -s for the service:
root@meet:/etc/nginx# curl -s http://127.0.0.1:9888/metrics
json: cannot unmarshal object into Go struct field videoBridgeStats.conference_sizes of type []int

root@meet:/etc/nginx# curl -s http://localhost:9100/jicofo
json: cannot unmarshal object into Go struct field videoBridgeStats.conference_sizes of type []int

Anyone else experianced the same problem?

Best Regards
Thomas Nissen

**Comment by palle64** [comment]
We have the samme issue. Any ideas to make it work?

**Comment by pdarcos** [comment]
I also have the exact same issue, the only difference is that I'm not using docker, but rather running on bare metal Debian 11.5

/username/go/bin/prometheus-jitsi-meet-exporter
json decoding error: json: cannot unmarshal string into Go struct field videoBridgeStats.conference_sizes of type []int

Has anyone figured out how to fix this?

**Comment by pdarcos** [comment]
I guess this project is no longer being maintained.
Too bad. Anyone know of a different alternative that is being kept up to date?

**Comment by t2d** [comment]
We are not experiencing this error. However, any PR is welcome to address this problem.

**Comment by L3o-pold** [comment]
You seems to query stats from Jicofo endpoint (`:8888/stats`) instead of JVB endpoint (`/colibri/stats`)
