### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by pdarcos** [systemli/prometheus-jitsi-meet-exporter#119]
Or has this been abandoned?

Thx

**Comment by t2d** [comment]
Why do you think it has been abandoned?

**Comment by pdarcos** [comment]
Because there doesn't seem to be any PRs for a long time except package updates.

For example, the bug that I and others have reported [here](https://github.com/systemli/prometheus-jitsi-meet-exporter/issues/106) doesn't seem to be addressed. in my case I experience the json decoding error even on non-docker installs.

**Comment by pdarcos** [comment]
Specifically I get this error all the time which makes this exporter unworkable with current versions of jitsi-meet:

"json decoding error: json: cannot unmarshal object into Go struct field videoBridgeStats.conference_sizes of type []int"

And I'm compiling the exporter and running it on bare metal, so it's not a docker issue

**Comment by t2d** [comment]
No, we're running this project live every day. We will fix any problem that occurs. However, we won't fix problems where we don't know how to replicate this issue. Patches are still welcome, of course.
