### ISSUE TITLE
System metrics are not collected

### ISSUE THREAD

**Issue by pmp02** [systemli/prometheus-jitsi-meet-exporter#20]
Hi,

I have just deployed the exporter with docker for a running Jitsi instance (also docker) and everything seems to be working fine except the System metrics.

I am using the [Jitsi Meet & System](https://grafana.com/grafana/dashboards/12282) Grafana Dashboard and the System metrics are not being populated (always show no data).

Are these supposed to be collected by the collector as well or I should be doing something else for the system metrics?

Thank you for the exporter, it is very useful! Great job!

**Comment by 0x46616c6b** [comment]
Hey,

thanks for using the Exporter and bringing that up. The system metrics are collected by the node-exporter which is needed to configure by your own. For the context of running the exporter and jitsi inside a container that doesn't make sense. For that case you need to collect the container metrics. This would be a nice addition for another dashboard.

**Comment by pmp02** [comment]
Thank you for the explanation, this is clear and makes sense!
