### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by Warlock667** [systemli/prometheus-jitsi-meet-exporter#25]
Hi,

I am using the prometheus-jitsi-meet-exporter 1.1.2 on Ubuntu 20.04 with Jitsi Meet 2.0.5390 on Ubuntu 20.04.
I do get some metrics, but a lot of the interesting stuff is missing, although a conference is running. Of course there are some that shoud be 0 like jitsi_total_failed_conferences, but the interesting stuff like jitsi_rtt_aggregate  or jitsi_bit_rate are missing, too.

Working metrics:
jitsi_threads 272
jitsi_total_conferences_created 21
jitsi_largest_conference 2
jitsi_conferences 1
jitsi_participants 2

not working metrics:
jitsi_bit_rate_download 0
jitsi_bit_rate_upload 0
jitsi_packet_rate_download 0
jitsi_packet_rate_upload 0
jitsi_loss_rate_download 0
jitsi_loss_rate_upload 0
jitsi_jitter_aggregate 0
jitsi_rtt_aggregate 0
jitsi_audiochannels 0
jitsi_videochannels 0
jitsi_videostreams 0
jitsi_total_loss_controlled_participant_seconds 0
jitsi_total_loss_limited_participant_seconds 0
jitsi_total_loss_degraded_participant_seconds 0
jitsi_total_conference_seconds 0
jitsi_total_conferences_completed 0
jitsi_total_failed_conferences 0
jitsi_total_partially_failed_conferences 0
jitsi_total_data_channel_messages_received 0
jitsi_total_data_channel_messages_sent 0
jitsi_total_colibri_web_socket_messages_received 0
jitsi_total_colibri_web_socket_messages_sent 0

Does anyone have a hint for me why those metrics are missing ?

Bye, Dirk

**Comment by 0x46616c6b** [comment]
You need to activate the statistics in the videobridge. Here is the documentation: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md

**Comment by Warlock667** [comment]
Doh!
I promise to write 100 times "Next time I'm gonna read the friendly manual first" without Paste&Copy or any loops.

Works now like a charm :-)

Thanks a lot !
