### ISSUE TITLE
how configure stats endpoint

### ISSUE THREAD

**Issue by spprod35** [systemli/prometheus-jitsi-meet-exporter#3]
Hi,

I'm looking to configure the Jitsi url for the stats:
http://jitsi:8888/stats

I cannot find any specific documentation on this point.
What is the procedure to activate statistics with an 8888 URL without colibir in the url?
To have stats compatible with this export

Thank

**Comment by 0x46616c6b** [comment]
In default installation on debian the video-bridge exports basic metrics in json format under `/stats`. The listening port depends on the configuration of the video-bridge. For Debian installed packages it will be port 8888.

**Comment by 0x46616c6b** [comment]
See #4
