### ISSUE TITLE
Most metrics not changing

### ISSUE THREAD

**Issue by jpds** [systemli/prometheus-jitsi-meet-exporter#4]
I'm using the latest Jitsi packages and prometheus-jitsi-meet-exporter 1.1.1 on a Debian 10 server.

```
$ dpkg -l | grep jitsi
ii  jitsi-meet                            2.0.4548-1                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                    1.0.4074-1                   all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver                 1.0.4074-1                   all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                        1.0.4074-1                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.4074-1                   all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                    2.1-197-g38256192-1          all          WebRTC compatible Selective Forwarding Unit (SFU)
```

For some reason, only the `jitsi_conferences`, `jitsi_participants` and `jitsi_total_conferences_created` metrics change in a Jitsi meeting with 8 participants - all the other counters stay at 0.

I haven't made any special changes to the built-in Jitsi stats endpoint settings.

**Comment by 0x46616c6b** [comment]
You need to activate the rest api (https://github.com/systemli/ansible-role-jitsi-meet/blob/master/templates/videobridge/config.j2#L16) and enable statistics (https://github.com/systemli/ansible-role-jitsi-meet/blob/master/templates/videobridge/sip-communicator.properties.j2#L3).

After that, you can use the colibri stats endpoint -> http://localhost:8080/colibri/stats

**Comment by jpds** [comment]
@0x46616c6b Thank you very much for that, now it's working, but does this mean that I need to have two instances of the exporter running?

Specifying the `-videobridge-url` flag twice seems to only scrape one URL.

**Comment by 0x46616c6b** [comment]
No, the basic /stats endpoint exposes not all metrics, the `/colibri/stats` endpoint exposes all metrics, also the basic ones. So there is no need to run two instances.
