### ISSUE TITLE
Fails to fetch from https endpoint

### ISSUE THREAD

**Issue by MartijnHols** [systemli/prometheus-jitsi-meet-exporter#41]
When using https for the videobridge url, the containers fails with a "x509: certificate signed by unknown authority" error. This seems to be due to the scratch image missing the SSL certificates needed by Go. I worked around the issue by mounting `/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro`, which may be a useful workaround for someone else, but it would be nice if this worked out of the box.

**Comment by 0x46616c6b** [comment]
Nice catch! We use the exporter only from internal and not use https. I will add ca-certificates to the Docker Image asap.

**Comment by 0x46616c6b** [comment]
The problem should be fixed in d87c5f60005aed938d187454aa1b7b41bcc5d406. The Docker image is pushed, you can test it with newest `latest` tag. If you acknowledge that this solves your issue I will create a new tagged release.

**Comment by MartijnHols** [comment]
It works, thanks!
