### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by timowevel03** [systemli/prometheus-jitsi-meet-exporter#46]
Hey,

I got issues setting it up on my Ubuntu server. I run

docker run -p 9888:9888 systemli/prometheus-jitsi-meet-exporter:latest -videobridge-url http://127.0.0.1:8080/colibri/stats

but nothing happens.

https://prnt.sc/12ysz8q

Thanks in advance.

**Comment by 0x46616c6b** [comment]
The exporter only logs errors. If the docker container is running you can try to fetch the metrics like `curl localhost:9888/metrics`.

**Comment by timowevel03** [comment]
scrape error: Get "http://127.0.0.1:8888/stats": dial tcp 127.0.0.1:8888: connect: connection refused

**Comment by 0x46616c6b** [comment]
Then you should check the docker networking. It seems that 127.0.0.1 inside the container is not 127.0.01 on your host network. You can try to run the container in host network mode (`--network host`)

**Comment by timowevel03** [comment]
https://prnt.sc/12yz57n

https://prnt.sc/12yz4fj

Am I doing anything wrong?

**Comment by timowevel03** [comment]
So your suggestion seemed to work, but I cant add it in Grafana

**Comment by 0x46616c6b** [comment]
I guess you need to understand how the monitoring with Prometheus works.

First, the exporter only give you the metrics for the service. The metrics needs to be scraped by Prometheus. Prometheus fetches and stores the metrics as time series. Also, Prometheus exposes an api to query the stored metrics. So you will add Prometheus to Grafana as a datasource not the exporter directly.

**Comment by timowevel03** [comment]
Could you kindly tell me how to configure it? That doesnt help me a lot^^^
I got prometheus installed, added
- job_name: 'jitsi'

    # Override the global default and scrape targets from this job every 5 seco>
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9888']

to the config. What has to be the target? And which URL has to be added in the Grafana Prometheus Settings then?

Thanks.

**Comment by timowevel03** [comment]
Got it working, thanks.
