### ISSUE TITLE
Error unmarshaling float metrics from colibri stats

### ISSUE THREAD

**Issue by giangi** [systemli/prometheus-jitsi-meet-exporter#7]
Hello,

I was trying to use the exporter on a `colibri/stats` endpoint, and I noticed unmarshaling errors on rate metrics. I see that they are expected to be `int`, but indeed on my instance I get floating point values e.g. for `bit_rate_upload` and `bit_rate_download`. I have not looked into the source for those stats, but maybe defining them as `float64` is more compatible?

**Comment by danielcb** [comment]
should be fixed by #10

**Comment by jvwag** [comment]
wow, the timing is great! :) my upgrade just failed on this issue, but the fix is already there! tnx for that.

btw, the release is breaking so there is no new built artifact on hub.docker.com

**Comment by 0x46616c6b** [comment]
I can find the new automatically build docker image in the registry. Don't you find them?

**Comment by jvwag** [comment]
https://github.com/systemli/prometheus-jitsi-meet-exporter/runs/1292890537

Its probably not published due to the merge creating the same tag.

**Comment by mdavids** [comment]
Site note: I wonder why the bitrate is now (after the update of Jitsi)suddenly 0.5 by the way... Our Jitsi server is currently doing noting. A bitrate higher than 0 seems odd.

**Comment by 0x46616c6b** [comment]
New release should fix the problem: https://github.com/systemli/prometheus-jitsi-meet-exporter/releases/tag/1.1.2

For the Docker Image it could be need some time until the new version is in the registry.

**Comment by 0x46616c6b** [comment]
> https://github.com/systemli/prometheus-jitsi-meet-exporter/runs/1292890537
> 
> Its probably not published due to the merge creating the same tag.
> 
> Both tags (latest, digest: 3172a8ee41e3) and (1.1.2, digest: 3f28930621c3) are not fixing the issue.
> 
> `json: cannot unmarshal number 0.5 into Go struct field videoBridgeStats.bit_rate_download of type int`

The issue was fixed in #10
